// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC0krgjh16k4gLD852ZdUipHTPCAUXfSw',
    appId: '1:224849973423:web:c12fd330749ff1b9f0045a',
    messagingSenderId: '224849973423',
    projectId: 'boostseller-ea2bf',
    authDomain: 'boostseller-ea2bf.firebaseapp.com',
    storageBucket: 'boostseller-ea2bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2IhnYYjIAwlzslVY03eRcNAzKrTGEkQ',
    appId: '1:224849973423:android:9628c9569858bed6f0045a',
    messagingSenderId: '224849973423',
    projectId: 'boostseller-ea2bf',
    storageBucket: 'boostseller-ea2bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6YcwUhL0rOYiqrwXZ4POj3T7OhlZqhhA',
    appId: '1:224849973423:ios:14d8bc8c3778c560f0045a',
    messagingSenderId: '224849973423',
    projectId: 'boostseller-ea2bf',
    storageBucket: 'boostseller-ea2bf.firebasestorage.app',
    iosBundleId: 'ai.boostseller.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6YcwUhL0rOYiqrwXZ4POj3T7OhlZqhhA',
    appId: '1:224849973423:ios:14d8bc8c3778c560f0045a',
    messagingSenderId: '224849973423',
    projectId: 'boostseller-ea2bf',
    storageBucket: 'boostseller-ea2bf.firebasestorage.app',
    iosBundleId: 'ai.boostseller.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC0krgjh16k4gLD852ZdUipHTPCAUXfSw',
    appId: '1:224849973423:web:58e1eb16cf7f7282f0045a',
    messagingSenderId: '224849973423',
    projectId: 'boostseller-ea2bf',
    authDomain: 'boostseller-ea2bf.firebaseapp.com',
    storageBucket: 'boostseller-ea2bf.firebasestorage.app',
  );
}
