Map<String, Map<String, String>> localizedValues = {
  'en': {
    'Please select your role!': 'Please select your role!',
    'Hostess': 'Hostess',
    'Sales Person': 'Sales Person',
    'English': 'English',
    'Russian': 'Russian',
    'Welcome': 'Welcome',
    'Login to your account': 'Login to your account',
    'Email': 'Email',
    'Password': 'Password',
    'Forgot Password?': 'Forgot Password?',
    'Login': 'Login',
    'Don’t have account?': 'Don’t have account?',
    'Create Now': 'Create Now',
    'pendding_message': 'Your account is pending admin approval.',
    'role_invalid_message':
        'This role does not match your selection. Please select the correct role.',
    'ajax_error_message':
        'There was a problem communicating with the server. Please try again.',
    'email_empty_message': 'Email is required. Please enter a email.',
    'email_invalid_message': 'Please enter a valid email.',
    'password_invalid_message': 'Password must be at least 6 characters.',
    'password_match_error_message': 'Passwords do not match.',
    'all fileds_invalid_message': 'Please fill all fields.',
    'Register': 'Register',
    'Create a new account': 'Create a new account',
    'Name': 'Name',
    'Phone Number': 'Phone Number',
    'Password Confirm': 'Password Confirm',
    'Already have account?': 'Already have account?',
    'All fields are required. Please check your input.':
        'All fields are required. Please check your input.',
    'Verification': 'Verification',
    'verify_phone_message':
        'Verify your phone number to continue. \n We will send OTP to your phone number.',
    'verify_email_message':
        'Verify your email to continue. \n We will send OTP to your email.',
    'Send OTP': 'Send OTP',
    'Use Email Instead': 'Use Email Instead',
    'Use Phone Instead': 'Use Phone Instead',
    'Your phone number is {number}': 'Your phone number is {number}',
    'Your email is {email}': 'Your email is {email}',
    'otp_verify_message':
        'Please enter the verification code \n sent to your email.',
    'Email OTP': 'Email OTP',
    'Mobile OTP': 'Mobile OTP',
    'Verify': 'Verify',
    "If you didn't receive a code,": "If you didn't receive a code,",
    'Resend': 'Resend',
    'Forgot Password': 'Forgot Password',
    'Enter your phone number to reset password.':
        'Enter your phone number to reset password.',
    'Enter your email to reset password.':
        'Enter your email to reset password.',
    'Change Password': 'Change Password',
    'Enter your new password': 'Enter your new password',
    'Enter your confirmation password': 'Enter your confirmation password',
    'Change': 'Change',
    'Awaiting Approval': 'Awaiting Approval',
    'pendding_title':
        "Your account is under review.\nYou'll be notified once approved by the admin.",
    'New Lead': 'New Lead',
    'Interest': 'Interest',
    'ID': 'ID',
    'Add': 'Add',
    'Reset': 'Reset',
    'Leads': 'Leads',
    'lead_list_title': 'Please add a new lead or check previous leads.',
    'No leads found.': 'No leads found.',
    'You haven’t added any leads yet.': 'You haven’t added any leads yet.',
    'Lead Detail': 'Lead Detail',
    'Return': 'Return',
    'Register Date': 'Register Date',
    'less ...': 'less ...',
    'more...': 'more...',
    'Next': 'Next',
    'Close': 'Close',
    'Select Language': 'Select Language',
    'No Notifications': 'No Notifications',
    'empty_notification_message':
        "You currently have no new notifications.\nPlease check back later or wait for real-time updates—we’ll keep you informed.",
    'ago': 'ago',
    'Work with leads!': 'Work with leads!',
    'Assigned': 'Assigned',
    'Accepted': 'Accepted',
    'No Assigned Leads': 'No Assigned Leads',
    'No Accepted Leads': 'No Accepted Leads',
    'assigned_empty':
        "You haven’t received any new lead assignments yet.\nPlease check Do Not Disturb mode or refresh the list.",
    'accepted_empty':
        "You have not accepted any leads yet.\nOnce you accept a lead, it will appear here.",
    'Score': 'Score',
    'Conversion': 'Conversion',
    'Responsiveness': 'Responsiveness',
    'Effectiveness': 'Effectiveness',
    'Completed': 'Completed',
    'Setting': 'Setting',
    'Do Not Disturb': 'Do Not Disturb',
    'Logout': 'Logout',
    'Total': 'Total',
    'Accept': 'Accept',
    'Skip': 'Skip',
    'Lead assigned to you': 'Lead assigned to you',
    "Let’s start your work with lead!": "Let’s start your work with lead!",
    'Focus Mode': 'Focus Mode',
    'disturb_active':
        'You are currently in "Do Not Disturb" mode.\n\nNo new leads will be assigned until you turn it off.',
    'disturb_deactive':
        'You are available to receive new leads.\n\nTurn on "Do Not Disturb" to pause lead assignments.',
    'Confirm & Accept': 'Confirm & Accept',
    'Lead Successfully Completed!': 'Lead Successfully Completed!',
    'complete_title':
        'Well done!\nYou’ve successfully completed the sales process. Below is the journey this lead followed:',
    'complete_done':
        'Great job!\nKeep up the excellent work and\ncontinue closing more leads\nYour dedication is paying off!',
    'Lead Successfully Closed!': 'Lead Successfully Closed!',
    'closed_title':
        'This lead was closed before completion.\nBelow is the progress made before it stopped:',
    'closed_done':
        'Lead Closed!\nNot all leads close with a win, and that’s okay.\nEvery lead is a learning experience—on to the next!',
    'Advance': 'Advance',
    'role_empty_message': 'Your role is not selected. Please your select role.',
    'role_mismatch_message':
        'This role does not match your selection. Please select the correct role.',
    'login_success_message': 'Logged in successfully!',
    'user_not_found_message': 'User not found. Please register first.',
    'password_mismatch_message':
        'Password is Invalid. Please enter correct password.',
    'send_otp_success_message':
        'OTP sent successfully! Please check your email.',
    'send_otp_fail_message':
        'Sorry! We could not send OTP. Your email is not real.',
    'verify_success_message': 'OTP verified and Registered successfully!',
    'expire_message': 'Invalid or expired OTP. Please click Resend button.',
    'verify_error_message': 'OTP verification failed. Please try again.',
    'register_success_message': 'Register Successful!',
    'user_exist_message':
        'User already exist.Please check your identity infomation.',
    'register_fail_message': 'Failed to register. Please try again.',
    'invalid_phone_number': 'Please enter a phone number.',
    'change_password_success_message': 'Password Changed Successfully!',
    'change_password_error_message':
        'Failed to change password. Please try again.',
    'lead_add_success_message': 'Lead added successfully.',
    'lead_fail_success_message': 'Failed to add lead. Please try again.',
    'data_load_error_message': 'Failed to load data from server.',
    'lead_load_error_message': 'Failed to load leads data from server.',
    'interest_load_failed_message':
        'Failed to fetch interests. Please try again.',
    'not_found_interest_message': 'Not found Interests.',
    'not_found_lead_additional_data': 'Not found LeadAdditional Fields.',
    'lead_additional_data_failed': 'Failed to fetch data.Please try again.',
    'notification_load_failed_message':
        'Failed to get notifications. Please try again.',
    'closed_lead_failed_message': 'Failed to close new lead. Please try again.',
    'submit_error_message': 'Failed to submit data.',
    'disturb_setting_success':
        'Do Not Disturb mode is configured successfully!',
    'Lead accepted successfully': 'Lead accepted successfully!',
    'not_found_stages':
        'Sales stage is not defined. Please wait until configured sales stage setting.',
    'move_next_Stage_message': 'Moved to the next stage successfully.',
    'avatar_upload_success': 'Uploaded profile image successful!',
    'avatar_upload_failed': 'Failed to upload profile image.',
    'Add reason & comment': 'Add reason & comment',
    'Reason': 'Reason',
    'Comment': 'Comment',
    'Continue': 'Continue',
    'reason_empty': 'Please select the reason.',
    'comment_required': 'Comment is required. Please type in commnet.',
    '{label} is required': '{label} is required.',
    'ID is required': 'ID is required.',
    'Please select an interest': 'Please select an interest.',
    'Name is required': 'Name is required.',
    'Phone number is required': 'Phone number is required.',
    'hostess': 'hostess',
    'performer': 'performer',
    'Exit App?': 'Exit App?',
    'Do you really want to close the application?':
        'Do you really want to close the application?',
    'Cancel': 'Cancel',
    'Exit': 'Exit',
    'comment_hint': 'Please enter comment.',
    'currency_comment': 'Enter amount.',
    'date_comment': 'Please select date.',
    'photo_required': 'Please select an image.',
    'file_required': 'Please select a file.',
    'checkbox_group_required': 'Please select at least one.',
    'No file selected': 'No file selected.',
    'Tap to capture': 'Tap to capture.',
    'Starting...': 'Starting...',
    'Loading preferences...': 'Loading preferences...',
    'Checking login token...': 'Checking login token...',
    'Initializaing firebase...': 'Initializaing firebase...',
    'Preparing data...': 'Preparing data...',
    'Launching...': 'Launching...',
    'Admin Email': 'Admin Email',
    'admin_empty_message':
        'Admin email is invalid or not exist Approved admin.',
    'disturb_on_message': 'Do Not Disturb mode is set as On.',
    'disturb_off_message': 'Do Not Disturb mode is set as Off.',
    'lead_exist_message': 'Another Lead already exists with same lead data.',
  },
  'ru': {
    'Please select your role!': 'Пожалуйста, выберите вашу роль!',
    'Hostess': 'Хостесс',
    'Sales Person': 'Продавец',
    'English': 'Английский',
    'Russian': 'Русский',
    'Welcome': 'Добро пожаловать',
    'Login to your account': 'Войдите в свою учетную запись',
    'Email': 'Электронная почта',
    'Password': 'Пароль',
    'Forgot Password?': 'Забыли пароль?',
    'Login': 'Авторизоваться',
    'Don’t have account?': 'Нет аккаунта?',
    'Create Now': 'Создать сейчас',
    'pendding_message': 'Ваша учетная запись ожидает одобрения администратора.',
    'role_invalid_message':
        'Эта роль не соответствует вашему выбору. Пожалуйста, выберите правильную роль.',
    'ajax_error_message':
        'Возникла проблема связи с сервером. Попробуйте еще раз.',
    'email_empty_message': 'Введите адрес электронной почты.',
    'email_invalid_message': 'Введите действительный адрес электронной почты',
    'password_invalid_message': 'Пароль должен содержать не менее 6 символов.',
    'password_match_error_message': 'Пароли не совпадают.',
    'all fileds_invalid_message': 'Пожалуйста, заполните все поля.',
    'Register': 'Зарегистрироваться',
    'Create a new account': 'Создать новую учетную запись',
    'Name': 'Имя',
    'Phone Number': 'Номер телефона',
    'Password Confirm': 'Подтвердите пароль',
    'Already have account?': 'У вас уже есть аккаунт?',
    'All fields are required. Please check your input.':
        'Все поля обязательны. Проверьте введенные данные.',
    'Verification': 'Проверка',
    'verify_phone_message':
        'Подтвердите свой номер телефона, чтобы продолжить. \n Мы отправим OTP на ваш номер телефона.',
    'verify_email_message':
        'Подтвердите свой адрес электронной почты, чтобы продолжить. \n Мы отправим одноразовый пароль на ваш адрес электронной почты.',
    'Send OTP': 'Отправить одноразовый пароль',
    'Use Email Instead': 'Вместо этого используйте электронную почту',
    'Use Phone Instead': 'Используйте телефон вместо этого',
    'Your phone number is {number}': 'Ваш номер телефона {number}',
    'Your email is {email}': 'Ваш адрес электронной почты {email}',
    'otp_verify_message':
        'Введите проверочный код, \n отправленный на вашу электронную почту.',
    'Email OTP': 'Электронная почта OTP',
    'Mobile OTP': 'Мобильный OTP',
    'Verify': 'Проверять',
    "If you didn't receive a code,": "Если вы не получили код,",
    'Resend': 'Отправить повторно',
    'Forgot Password': 'Забыли пароль',
    'Enter your phone number to reset password.':
        'Введите свой номер телефона для сброса пароля.',
    'Enter your email to reset password.':
        'Введите свой адрес электронной почты для сброса пароля.',
    'Change Password': 'Изменить пароль',
    'Enter your new password': 'Введите новый пароль',
    'Enter your confirmation password': 'Введите ваш пароль подтверждения',
    'Change': 'Изменять',
    'Awaiting Approval': 'Ожидает одобрения',
    'pendding_title':
        "Ваша учетная запись находится на рассмотрении.\nВы получите уведомление после одобрения администратором.",
    'New Lead': 'Новый Лид',
    'Interest': 'Интерес',
    'ID': 'ИДЕНТИФИКАТОР',
    'Add': 'Добавлять',
    'Reset': 'Перезагрузить',
    'Leads': 'Лиды',
    'lead_list_title':
        'Пожалуйста, добавьте новый лид или проверьте предыдущие лиды.',
    'No leads found.': 'Лидов не найдено.',
    'You haven’t added any leads yet.': 'Вы пока не добавили ни одного лида.',
    'Lead Detail': 'Подробности свинца',
    'Return': 'Возвращаться',
    'Register Date': 'Дата регистрации',
    'less ...': 'меньше ...',
    'more...': 'более...',
    'Next': 'Следующий',
    'Close': 'Закрывать',
    'Select Language': 'Выберите язык',
    'No Notifications': 'Нет уведомлений',
    'empty_notification_message':
        "В настоящее время у вас нет новых уведомлений.\nПожалуйста, проверьте позже или дождитесь обновлений в реальном времени — мы будем держать вас в курсе.",
    'ago': 'назад',
    'Assigned': 'Назначенный',
    'Accepted': 'Принял',
    'No Assigned Leads': 'Нет назначенных лидов',
    'No Accepted Leads': 'Нет принятых лидов',
    'assigned_empty':
        "Вы пока не получили новых назначений на лиды.\nПожалуйста, проверьте режим «Не беспокоить» или обновите список.",
    'accepted_empty':
        "Вы пока не приняли ни одного лида.\nПосле того, как вы примете лид, он появится здесь.",
    'Work with leads!': 'Работайте с лидами!',
    'Score': 'Счет',
    'Conversion': 'Конверсия',
    'Responsiveness': 'Отзывчивость',
    'Effectiveness': 'Эффективность',
    'Completed': 'Завершенный',
    'Setting': 'Параметр',
    'Do Not Disturb': 'не беспокоить',
    'Logout': 'Выйти',
    'Total': 'Общий',
    'Accept': 'Принимать',
    'Skip': 'Пропускать',
    'Lead assigned to you': 'Лид, назначенный вам',
    "Let’s start your work with lead!": "Давайте начнем вашу работу со свинца!",
    'Focus Mode': 'Режим фокусировки',
    'disturb_active':
        'В настоящее время вы находитесь в режиме «Не беспокоить».\n\nНовые лиды не будут назначаться, пока вы его не выключите.',
    'disturb_deactive':
        'Вы можете получать новые лиды.\n\nВключите функцию «Не беспокоить», чтобы приостановить назначение лидов.',
    'Confirm & Accept': 'Подтвердить и принять',
    'Lead Successfully Completed!': 'Задание успешно выполнено!',
    'complete_title':
        'Молодец!\nВы успешно завершили процесс продажи. Ниже представлен путь, который прошел этот лид:',
    'complete_done':
        'Отличная работа! Продолжайте в том же духе и заключайте больше сделок. Ваша преданность делу окупается!',
    'Lead Successfully Closed!': 'Заявка успешно закрыта!',
    'closed_title':
        'Это направление было закрыто до завершения.\nНиже представлен прогресс, достигнутый до его остановки:',
    'closed_done':
        'Лид закрыт!\nНе все лиды завершаются победой, и это нормально.\nКаждый лид — это опыт обучения — вперед к следующему!',
    'Advance': 'Продвигать',
    'role_empty_message': 'Ваша роль не выбрана. Пожалуйста, выберите роль.',
    'role_mismatch_message':
        'Эта роль не соответствует вашему выбору. Пожалуйста, выберите правильную роль.',
    'login_success_message': 'Авторизация выполнена успешно!',
    'user_not_found_message':
        'Пользователь не найден. Пожалуйста, зарегистрируйтесь сначала.',
    'password_mismatch_message':
        'Пароль недействителен. Введите правильный пароль.',
    'send_otp_success_message': 'OTP успешно отправлен! Проверьте почту.',
    'send_otp_fail_message':
        'Извините! Мы не смогли отправить OTP. Ваш email не настоящий.',
    'verify_success_message': 'OTP проверен и успешно зарегистрирован!',
    'expire_message':
        'Неверный или просроченный OTP. Нажмите кнопку «Повторить».',
    'verify_error_message': 'Проверка OTP не удалась. Попробуйте еще раз.',
    'user_exist_message':
        'Пользователь уже существует. Проверьте данные своей личности.',
    'register_fail_message':
        'Не удалось зарегистрироваться. Попробуйте еще раз.',
    'invalid_phone_number': 'Введите номер телефона.',
    'change_password_success_message': 'Пароль успешно изменен!',
    'change_password_error_message':
        'Не удалось сменить пароль. Попробуйте еще раз.',
    'lead_add_success_message': 'Лид успешно добавлен.',
    'lead_fail_success_message': 'Не удалось добавить лид. Попробуйте еще раз.',
    'data_load_error_message': 'Не удалось загрузить данные с сервера.',
    'lead_load_error_message': 'Не удалось загрузить данные о лидах с сервера.',
    'interest_load_failed_message':
        'Не удалось получить интересы. Попробуйте еще раз.',
    'not_found_interest_message': 'Не найдено Интересы.',
    'not_found_lead_additional_data':
        'Не найдено дополнительных полей LeadAdditional.',
    'lead_additional_data_failed':
        'Не удалось получить данные. Попробуйте еще раз.',
    'notification_load_failed_message':
        'Не удалось получить уведомления. Попробуйте еще раз.',
    'closed_lead_failed_message':
        'Не удалось закрыть новый лид. Попробуйте еще раз.',
    'submit_error_message': 'Не удалось отправить данные.',
    'disturb_setting_success': 'Режим «Не беспокоить» успешно настроен!',
    'Lead accepted successfully': 'Заявка успешно принята!',
    'not_found_stages':
        'Этап продаж не определен. Пожалуйста, подождите, пока не будут настроены параметры этапа продаж.',
    'move_next_Stage_message': 'Успешно перешли на следующий этап.',
    'avatar_upload_success': 'Изображение профиля успешно загружено!',
    'avatar_upload_failed': 'Не удалось загрузить изображение профиля.',
    'Add reason & comment': 'Добавить причину и комментарий',
    'Reason': 'Причина',
    'Comment': 'Комментарий',
    'Continue': 'Продолжать',
    'reason_empty': 'Пожалуйста, выберите причину.',
    'comment_required':
        'Комментарий обязателен. Пожалуйста, введите комментарий.',
    '{label} is required': '{label} требуется.',
    'ID is required': 'Требуется удостоверение личности.',
    'Please select an interest': 'Пожалуйста, выберите интерес.',
    'Name is required': 'Имя обязательно.',
    'Phone number is required': 'Номер телефона обязателен.',
    'hostess': 'хозяйка',
    'performer': 'исполнитель',
    'Exit App?': 'Выйти из приложения?',
    'Do you really want to close the application?':
        'Вы действительно хотите закрыть приложение?',
    'Cancel': 'Отмена',
    'Exit': 'Выход',
    'comment_hint': 'Пожалуйста, введите комментарий.',
    'currency_comment': 'Введите сумму.',
    'date_comment': 'Пожалуйста, выберите дату.',
    'photo_required': 'Пожалуйста, выберите изображение.',
    'file_required': 'Пожалуйста, выберите файл.',
    'checkbox_group_required': 'Пожалуйста, выберите хотя бы один вариант.',
    'No file selected': 'Файл не выбран.',
    'Tap to capture': 'Нажмите, чтобы сделать снимок.',
    'Starting...': 'Начинаем...',
    'Loading preferences...': 'Загрузка настроек...',
    'Checking login token...': 'Проверка токена входа...',
    'Initializaing firebase...': 'Инициализация firebase...',
    'Preparing data...': 'Подготовка данных...',
    'Launching...': 'Запуск...',
    'Admin Email': 'Электронная почта администратора',
    'admin_empty_message':
        'Адрес электронной почты администратора недействителен или не существует. Одобренный администратор.',
    'disturb_on_message': 'Режим «Не беспокоить» включен.',
    'disturb_off_message': 'Режим «Не беспокоить» отключен.',
    'lead_exist_message': 'Другой лид с такими же данными уже существует.',
  },
};

String getText(String key, String lang, {Map<String, String>? args}) {
  String text = localizedValues[lang]?[key] ?? key;
  if (args != null) {
    args.forEach((k, v) {
      text = text.replaceAll('{$k}', v);
    });
  }
  return text;
}
